# Generated by Django 4.2.5 on 2023-10-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('id_automatico', models.AutoField(primary_key=True, serialize=False)),
                ('sala', models.IntegerField(null=True)),
                ('referencia', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
