# Generated by Django 4.2.5 on 2023-10-01 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('status_dispositivo', models.CharField(choices=[('R', 'Reparação'), ('D', 'Defeito'), ('F', 'Funcionando')], default='F', max_length=30)),
                ('registro_criado', models.DateField(auto_now_add=True, null=True)),
                ('registro_atualizado', models.DateField(auto_now=True, null=True)),
                ('detalhes', models.CharField(blank=True, max_length=200, null=True)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamento', to='dispositivos.dispositivos')),
            ],
        ),
    ]
