# Generated by Django 4.2.5 on 2023-10-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('falhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falha',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='falhas', to='dispositivos.dispositivos'),
        ),
        migrations.AlterField(
            model_name='falha',
            name='status_dispositivo',
            field=models.CharField(choices=[('F', 'Funcionando'), ('R', 'Reparação'), ('D', 'Defeito')], default='D', max_length=30),
        ),
    ]
