# Generated by Django 4.2.5 on 2023-11-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falhas', '0002_alter_falha_equipamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falha',
            name='status_dispositivo',
            field=models.CharField(choices=[('D', 'Defeito'), ('R', 'Reparação'), ('F', 'Funcionando')], default='D', max_length=30),
        ),
    ]
