# Generated by Django 4.2.5 on 2025-04-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falhas', '0003_alter_falha_status_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falha',
            name='status_dispositivo',
            field=models.CharField(choices=[('F', 'Funcionando'), ('R', 'Reparação'), ('D', 'Defeito')], default='D', max_length=30),
        ),
    ]
